methods delete and showAll added, fixed Adapted, Exception for getById
AKShipulya/stormnet pull request #7
Opened 2020-11-19 20:07 UTC by AKShipulya

@N0TARGET
Hi!
-was added methods delete() and showAll()
-was rework exception for method getById
-was fixed class Adapter

2020-11-20 08:34 UTC, N0TARGET requested changes

2020-11-20 08:34 UTC, N0TARGET commented on src/org/stormnet/library/controllers/BookController.java
> +    public List<Book> showAll() {
getAll

2020-11-20 08:34 UTC, N0TARGET commented on src/org/stormnet/library/adapter/Adapter.java
> +                    "Чобы добавить новую книгу, нажмите \"5\"\n" +
Use categories. At start you can offer to work with books, orders or users. And once you've choosen the category then  you are shown a menu to work with necessary category.

2020-11-20 08:34 UTC, N0TARGET commented on src/org/stormnet/library/dao/BookDao.java
> +        return baseOfBooks.getMapOfBooks().remove(id);
rename baseOfBooks to database

2020-11-20 08:34 UTC, N0TARGET commented on src/org/stormnet/library/interfaces/Dao.java
> +    List<T> showAll();
getAll

2020-11-20 08:34 UTC, N0TARGET commented on src/org/stormnet/library/services/BookService.java
> +            if (result == null) {
what the necessity throw an exception and catch it at the same place? Just to log? It's weird.

2020-11-22 10:48 UTC, AKShipulya commented on src/org/stormnet/library/services/BookService.java
> +            if (result == null) {
N0TARGET
it's was made so that when this exception is catched application can performing further but not crashed

2020-11-22 11:31 UTC, N0TARGET requested changes

2020-11-22 11:31 UTC, N0TARGET commented on src/org/stormnet/library/adapter/Adapter.java
> +                    System.out.println("Пожалуйста, введите название книги:");
move it to special classes which are responsible for necessary functionality since your method is too big

2020-11-22 11:31 UTC, N0TARGET commented on src/org/stormnet/library/services/BookService.java
> +            if (result == null) {
You are throwing the  exception and catching it at the same place. It does not make any sense. Rewrite it please

2020-12-27 16:05 UTC, merged